# Generated by Django 3.2.4 on 2021-06-05 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todomodel',
            old_name='titile',
            new_name='title',
        ),
    ]
